---
title: "課?<a0>?練習模<e7><89><88>"
author: "hsuchunju"
date: "2020-11-21"
output: output_format
params:
  id: "410973072"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
AA = c(Mary=176, John=188, Jenny= 165, Kate=170)
LL = list(
  Mary=list(176,"Taipei"),
  John=list(188,"New Taipei"),
  Jenny=list(165,"Taichung"),
  Kate=list(170,"Hualien")
)
```


## extract 1 element

```{r}
AA[[1]]
AA[1]
```


```{r}
LL[[1]]
LL[1]
```

```{r}
str(LL)
```


```{r}
str(LL[1])
LL[1]
```
```{r}
AA[c(1,4)]
LL[c(1,4)]
AA[c("Mary","Kate")]
LL[c("Mary","Kate")]
```

```{r}
a <- c(2, 5, 7)
a[[4]]
length(a)
```
```{r}
a[[4]] <- 8
print(a)
```

```{r}
oneorder <- 
  list(
restaurant = "すき家 Sukiya (新北三峽店)",
date = lubridate::mdy("Nov 10, 2020"),
order = list(
  list(
    item="蕃茄牛丼",
    quantity=1
  ) # 這裡少了一筆 "起司蕃茄牛丼"
),
total = 328)
```

```{r}
str(oneorder)
```

```{r}
#step 1 retrieve non-existence
oneorder[["order"]][[2]]
#step 2 assign value
oneorder[["order"]][[2]] <- 
  list(
    item = "起司番茄牛丼",
    quantuty = 1
  )
```

```{r}
str(oneorder)
```

```{r}
a <- c(2, 5, 7)
a[c(4,5)] <- c(8,12)
print(a)
```

```{r}
length(oneorder$order)
blue3 <- list(item = "牛丼飯", quantity = 1)

blue4 <- oneorder$order[[1]]
blue4$item <- "豬排飯"
blue4$quantity <- 1


oneorder[c(3,4)] <- list(blue3, blue4)
```

```{r}
str(oneorder)
```

```{r}
# 取出目前已有的子元素一個當模版
secondItem <- oneItem <- oneOrder$order[[1]]

oneItem$item <- "牛丼飯"
oneItem$quantity <- 1
secondItem$item <- "豬排飯"
secondItem$quantity <- 1

oneOrder$order[newOrders] <- list(
  oneItem, secondItem
)
```

```{r}
library(lubridate)
LL0 <- LL <- list(
  "Mary was born on", 
  ymd("1995-7-1"),
  "John was born on",
  ymd("1997-10-27")
  )
LL[[2]]
```

```{r}
LL[[2]] <- ymd("1995-7-8")
print(LL)
```

```{r}
oneorder$order[[1]]$quantity
oneorder$order[[1]]$quantity <- 2
oneorder
```

```{r}
LL[c(2,4)] <- list( ymd("1995-7-8"),ymd("1997-10-17")
)
print(LL)
```

```{r}
class(LL)
```

```{r}
oneOrder <- oneorder
```

```{r}
anotherOrder <- 
  list(
    restaurant="古橋飲食店",
    date=lubridate::mdy("Nov 9, 2020"),
    order=list(
      list(
        item="古早味排骨飯",
        quantity=1
      )
    ),
    total=89
  )
thirdOrder <-
  list(
    restaurant="Tijo Kitchen",
    date=lubridate::mdy("Nov 8, 2020"),
    order=list(
      list(
        item="韓式泡菜黑咖哩飯",
        quantity=1
      )
    )
  )
```


```{r}
allMyOrder <- 
  list(
    oneOrder,
    anotherOther,
    thirdOrder
  )
```

```{r}
allMyOrder = 
  list(
    oneOrder
  )
allMyOrder[c(2.3)] <- list(anotherOrder,thirdOrder)
allMyOrder
```

```{r}
a <- c("L", "K", "Z")
a <- a[-c(2)]
print(a)
```

```{r}
LL <- list('a', T, 183)
LL[c(1,3)] <- NULL 
print(LL) 
```

```{r}
a0 <- a <- c(John=178, Mary=170, Hanson=180)
names(a)

names(a) <- c("John", "Kate", "Hason")
names(a)

a <- a0
names(a)[[2]] <- "May"
names(a)
```

```{r}
?names
```

