---
title: "課?<a0>?練習模<e7><89><88>"
author: "hsuchunju"
date: "2020-10-25"
output: output_format
params:
  id: "410973072"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}

```
# Review R Basic(I)
```{r}
library(googlesheets4)
```
用指令安裝套件
```{r}
library(googlesheets4)
library(pillar)
```

```{r}
library(knitr)
purl("2020-10-25.Rmd")
```
值 -> 物件
```{r}
23 -> chia
16 -> chou
```

# Review R Basic (II)
```{r}
2
4
```
```{r}
my_108_total_credits <- 15
`_108_total_credits` <- 15
108_total_credits <- 15
_my_108_total_credits <- 15
my.108.total_credits <- 15
.108.total_credits <- 15 # 隱藏變數
.my.108.total_credits <- 15
我的108學年總學分數 <- 15
`我的108學年總學分數` <- 15 # 特殊名稱處理，`不是名稱的一部份
`.108.total_credits` <- 15
```

```{r}
a <- 15 # 變數設定
b <- a
# 呼叫a的值，用來設定變數b的值，相當於 b <- 15
# 把a指定給b
c <- y
#未創造出y
```

```{r}
a <- 6
# b不會跟著改變 沒有綁在一起
```

```{r}
sum(c(a,b))
```
```{r}
a+b
```
# Review R Basics(III) Atomic Vector
```{r}
a <- 6
b <- 15
y <- 22
c <- y
```

```{r}
myName <- "Mary"
```

```{r}
length(myName) # 查看物件本身代表幾個值。
```
```{r}
num1 <- 5
vNum1 <- c(2,5)
vNum2 <- c(2, num1)
```

```{r}
vNum1 <- vNum2
vNum2 <- c(2, vNum1)
```

```{r}
heightsOftheEntireClassroom <- c()

heightsOftheEntireClassroom2 <-c()
```

```{r}
heightOfAStudentComingInsideTheClassroom <- sample(165:200,1)
```

```{r}
# method 1: concatenate
heightsOftheEntireClassroom <- 
  c(
  heightsOftheEntireClassroom,
  heightOfAStudentComingInsideTheClassroom
)
```

```{r}
# method 2:
heightsOftheEntireClassroom2 <- 
  heightOfAStudentComingInsideTheClassroom
```

```{r}
c(5, "Mary") # non-Atomic
c(5,7)
c("John","Mary")
c(T,TRUE,F,FALSE)
c(T,T,F,F)
```

# Review R Basics(IV)Character
```{r}
num1<-5 # 非整數
num2<-5L # 整數

num1Vector<-c(5,6,7)
num2Vector<-c(5L,6L,7L)
```

```{r}
typeof(num1)
typeof(num2)
```


```{r}
object.size(num1)
object.size(num2)
```

```{r}
object.size(num1Vector)
object.size(num2Vector)
```

```{r}
char1Vector<-c("你好","How are you?")
```

```{r}
typeof(char1Vector)
class(char1Vector)
```

```{r}
dialogue <- c(
  '小明說："明天不用上課。"',
  '小花說："真的嗎？"'
)

dialogue # 顯示原始值的內容（含輸入時的引號）
cat(dialogue, sep="\n") # 顯示給人類看（含存出來）的值，sep="\n", 不同元素換行陳列。
writeLines(dialogue, "conversation.txt") # cat顯示的正是存出來樣貌。
```

```{r}
d1 <- c("小明說：","明天不用上課。")
d1
```
```{r}
d2 <- '小明說："明天不用上課。"'
d2
```
```{r}
context <- "老師說換行要寫\\n" # 請依下列情境輸入
cat(context)
```
```{r}

```

