---
title: "課?<a0>?練習模<e7><89><88>"
author: "hsuchunju"
date: "2020-10-27"
output: output_format
params:
  id: "410973072"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

# Review R Basics(VII) List

```{r}
library(lubridate)

# Date/Time class
purchasingTime <- 
  ymd_hms("2020-03-31T13:40:55Z")

# character
location <- "一芳"
item <- "水果茶"

# numeric
quantity <- 2

mingsPurchase <-
  list(
    purchasingTime, 
    location, 
    quantity, 
    item
  )
print(mingsPurchase)
```

```{r}
a <- c(2,5,10,16)
a
```

```{r}
mingsPurchase2 <-
  list(
    time = purchasingTime,
    'location' = location,
    "quantity" = quantity,
    `item name` = item
  )
print(mingsPurchase2)
```
```{r}
heights = c(
  mary=162,
  john=177,
  steve=180
)
```

```{r}
exampleList <- 
  list(
    c(4,6,10),
    list("Mary",173),
    TRUE
  )

print(exampleList)
```

```{r}
example2 <- list(
  list(2,"John"),
  list(3,"Mary")
)

print(example2)
```

```{r}
example2c <- c(
  c(2,5),
  c(4,6)
)
#c(2,5,4,6)
print(example2c)
```
```{r}
# 「**2杯**」「**水果茶**」
item1 <- list(
  quantity=2,
  `item name`="水果茶"
)
# 「**1杯**」「**日月紅茶**」
item2 <- list(
  quantity=1,
  `item name`="日月紅茶"
)

mingsPurchase3 <-
  list(
    time = purchasingTime,
    location = location,
    items=list(
      item1,
      item2
    )
  )

print(mingsPurchase3)
```
```{r}
student1 <-
  list(
    name = character(),
    id = character(),
    gmail = character(),
    googleClassroom =
      list(
        displayName = character()
      ),
    github =
      list(
        username = character(),
        repoUrl = character()
      ),
    homeworks = list(),
    exams = list(),
    list()
  )

names(student1) # 每個元素名稱
length(student1) # 元素個數
str(student1, 2) # 第一層基本元素架構
```
```{r}
hw1 <- list(
  date=ymd("2020-10-21"),
  grade=10
)
exam1 <- list(
  date=ymd("2020-10-28"),
  grade=50
)
student1 <-
  list(
    name = "Martin",
    id = "007",
    gmail = "mt@gm.ntpu.edu.tw",
    googleClassroom =
      list(
        displayName = "MT L"
      ),
    github =
      list(
        username = "tpemartin",
        repoUrl = "https://github.com/tpemartin/109-1-inclass-practice"
      ),
    homeworks = list(
      hw1
    ),
    exams = list(
      exam1
    ),
    list()
  )

str(student1, 2)
```

```{r}
categoryTemplate = 
  list(
    categoryName=character(),
    items = list(
    )
  )
saladCat <- 
  list(
    categoryName="沙拉套餐",
    items = list(
      list(
        "板煎雞腿排經典卡薩沙拉",203
      ),
      list(
        "炙燒鴨胸佐胡麻沙拉",203
      ),
      list(
        "煙燻鮭魚佐油醋沙拉",203
      )
    )
  )
print(saladCat)
```
```{r}
mingsPurchase3
library(jsonlite) # 不少同學這行會有Error，還記得如何排除嗎？
toJSON(mingsPurchase3)
```

```{r}
save(item2, saladCat, file="myObjects.rda")
```

```{r}
load("myObjects.rda")
```

# Reviwe for the first midterm exam

```{r}
my_108_total_credits <- 15
`_108_total_credits` <- 15
`108_total_credits` <- 15
`_my_108_total_credits`<- 15
my.108.total_credits <- 15
`.108.total_credits` <- 15 # 隱藏變數
.my.108.total_credits <- 15
我的108學年總學分數 <- 15
`我的108學年總學分數` <- 15 # 特殊名稱處理，`不是名稱的一部份
`.108.total_credits` <- 15
```

```{r}
我的年紀 <- 20
my_age <- 我的年紀
```

```{r}
vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum4 <- c() # 空向量

vNum3 <- c(vNum2, vNum1)
vNum4 <- c(vNum4, vNum1) # 向量疊代 （recursive vector concatenate）

vNum3
vNum4
```

```{r}
context <- "老師說換行要寫\\n"
cat(context)
```
```{r}
# 10位學生的主系
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')

typeof(majors10_char)
class(majors10_char)
```
```{r}
majors10_factor <- factor(majors10_char)
# 或
majors10_factor <- factor(
  c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
)

typeof(majors10_factor)
class(majors10_factor)
```
```{r}
majors10_char
majors10_factor
```
```{r}
as.integer(majors10_factor) 
```
```{r}
levels(majors10_factor)
```
```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) # 無法進行數值運算
stringInteger+2
```
```{r}
trueInteger <- as.integer(stringInteger)
class(trueInteger) # 可以進行數值運算
typeof(trueInteger)
trueInteger+2
```
```{r}
char3 <- c("小明","1","3")
as.integer(char3)
```
```{r}
studentId <- c(410773002, 410773015)
class(studentId)
as.character(studentId)
```
```{r}
library(lubridate)
```

```{r}
tpeTime <- ymd_hms("2020-03-18 13:52:40",
        tz="Asia/Taipei")

pgTime <- mdy_hms("Mar.18, 2020, 05:52:40",
                  tz="Europe/Lisbon")
```

```{r}
typeof(tpeTime)
class(tpeTime)
```
```{r}
tpeTime
print(tpeTime)
cat(tpeTime)
```
```{r}
cat(as.character(tpeTime))
```
```{r}
tpeTime2 <- ymd_hms("2010-03-18 16:52:40",
        tz="Asia/Taipei")
pgTime2 <- mdy_hms("Mar.01, 2020, 03:52:40",
                  tz="Europe/Lisbon")
```

```{r}
tpeTime3 <- 
  with_tz(tpeTime2, tzone="America/New_York")

print(tpeTime2)
print(tpeTime3)
```
```{r}
pgTime3 <- 
  with_tz(pgTime2, tzone="America/New_York")

print(pgTime2)
print(pgTime3)
```
```{r}
# Method 1: convert to UTC and pass as character
tpeTime_utc <- with_tz(tpeTime, tzone="UTC")
as.character(tpeTime_utc)
```
```{r}
tpeTime_iso8601 <- format_ISO8601(tpeTime, usetz=T)
tpeTime_iso8601
```
```{r}
tpeTime <- ymd_hms(tpeTime_iso8601)
tpeTime
```
```{r}
browseURL("https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit#gid=458686645")
```

```{r}
firstCommit <- ymd_hms("2020-03-11 14:16:43")
lastCommit <- ymd_hms("2020-03-11 14:34:33")

student1 <- c(firstCommit,lastCommit)
student1
class(student1)
```

