---
title: "課?<a0>?練習模<e7><89><88>"
author: "hsuchunju"
date: "2020-12-22"
output: output_format
params:
  id: "410973072"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
# Given some information
R <- 0.09
M <- 10000
T <- 3
# What I need to do
PDV <- 
{
  M/(1+R)**T
}
```

```{r}
getPDV <- function(R,M,T) 
{
  M/(1+R)**T
}
```

```{r}
getPDV(R=0.09, T=3, M=10000)
```

```{r}
debug(getPDV) 
getPDV(R=0.09, T=3, M=10000) 
undebug(getPDV)
```

```{r}
# 查詢函數formals arguments要求
formals(getPDV)
```

```{r}
# 查詢函數主體
body(getPDV)
```

```{r}
# body執行時若有物件不存在execution environment時要去找尋的environment
environment(getPDV)
```

```{r}
# Given some information
TT <- 3
# What I need to do
getPDV2 <- function(R,M){
  M/(1+R)**TT
}
```


```{r}
getPDV2(R=0.12, M=50000)
debug(getPDV2)
getPDV2(R=0.12, M=50000)
undebug(getPDV2)
```

```{r}
TT <- 3
getPDV2(R=0.12, M=50000)
```

```{r}
TT <- 1
getPDV2(R=0.12, M=50000)
```

```{r}
testFun <- function(){
  a <-2
  b <- 5
  a+b
}
testFun()
```

```{r}
testErrorFun <- function(){
  a <-2
  b <- 5
  output <- a+b
}
testErrorFun()
```

```{r}
testFun <- function(){
  a <-2
  b <- 5
  return(a+b)
  a^2+b*3
}
testFun()
```

```{r}
testFun <- function(){
  a <-2
  b <- 5
  invisible(a+b)
}
testFun()
output <- testFun()
output
```

```{r}
demandFun <- function(P) 5-3*P
supplyFun <- function(P) 1+0.5*P
market <- list(
  demand=demandFun,
  supply=supplyFun
)
```

```{r}
df0 <- function(f){
  epsilon <- 0.00001
  (f(epsilon)-f(0))/epsilon
}

df0(market$demand)
df0(market$supply)
```

